### ISSUE TITLE
is it possible to set it on each time when I enter into dired?

### ISSUE THREAD

**Issue by juniorxxue** [johannes-mueller/dired-gitignore.el#2]
I try to set it on each time when I enter into dired

so I add this line into my config
`(add-hook 'dired-mode-hook #'dired-gitignore-mode)`

It hints the error `No subdir-alist in myfolder`
I've also tested with other dired hooks and not succeeded.

so is it possible to set it on each time when I enter into dired?

Thanks

**Comment by johannes-mueller** [comment]
Thanks for the question.

Unfortunately this seems to be not trivially solvable. The problem is, that in the moment when `dired-mode-hook`s are run, the `dired` buffer is not yet set up, so directory entries are not yet found in the buffer.  It's also not trickable with some `run-with-timer` hacks as it seems.

So sorry, for the moment I don't see a feasible solution. If someone has an idea, comments and PRs welcome.

**Comment by johannes-mueller** [comment]
I think I have found a solution. 

[edited]

It turns out that the solution had some drawbacks. So I looked for a better one.

Now the more obvious approach

```elisp
(add-hook 'dired-mode-hook #'dired-gitignore-mode)
```
should work. 

@juniorxxue Can you please test?
